version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish --no-restore -c Release
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
  base-directory: WeatherLookup/bin/Release/netstandard2.0/