version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish --no-restore -c Release
  post_build:
    commands:
      - mv ./WeatherLookup/bin/Release/netstandard2.0/dist ./artifact
      - cp -R ./WeatherLookup/bin/Release/netstandard2.0/publish/wwwroot/css ./artifact/
    finally:
      - aws s3 cp ./artifact s3://blazor-weather-check --recursive