version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish --no-restore -c Release
  post_build:
    commands:
      - mv ./WeatherLookup/bin/Release/netstandard2.0/dist ./artifact
      - cp ./WeatherLookup/bin/Release/netstandard2.0/publish/wwwroot/css ./web-styles
    finally:
      - aws s3 cp ./artifact s3://blazor-weather-check --recursive
      - aws s3 cp ./web-styles s3://blazor-weather-check --recursive